version: '3.4'

services:
  express:
    image: express
    build:
      context: node_modules/express
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
